config/routes.rb
Rails.application.routes.draw do

  root 'bikes#index'
  get 'bikes/new' => 'bikes#new', as: :new_bike
  get 'bikes/:id' => 'bikes#show', as: :bike
  post 'bikes/' => 'bikes#create'

end

app/models/bike.rb
class Bike
	include Mongoid::Document
	field :name, type: String
	field :brand, type: String
	field :speed, type: Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	def index
		@bikes = Bike.all
	end

	def show
		@bike = Bike.find(params[:id])
	end

	def new
		@bike = Bike.new
	end

	def create
		# need code
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/index.html.erb
<h1>Cool Bikeshop</h1>

<ul>
	<% @bikes.each do |b| %>
		<li>
			<strong><%= b.name %></strong> <%= b.brand %> <%= b.speed %>
		</li>
	<% end %>
</ul>

app/views/bikes/new.html.erb
<h1>Add a new bike!</h1>

<%= form_for @bike do |f| %>
	Name: <%= f.text_field :name %>
	Brand: <%= f.text_field :brand %>
	Speed: <%= f.text_field :speed %>

	<%= f.submit "Add Bike!" %>
<% end %>
	
<%= link_to "Back to bike list", bike_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikeshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>